# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/ui/addCategoryWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddCategoryWindow(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(461, 190)
        Form.setStyleSheet("background-color: rgb(33, 33, 33);")
        application_icon = QtGui.QIcon()
        application_icon.addPixmap(QtGui.QPixmap(r"UI/icons/toDoList_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(application_icon)
        self.lineEdit_category = QtWidgets.QLineEdit(Form)
        self.lineEdit_category.setGeometry(QtCore.QRect(30, 50, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_category.setFont(font)
        self.lineEdit_category.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px\n"
"}")
        self.lineEdit_category.setText("")
        self.lineEdit_category.setObjectName("lineEdit_category")
        self.btn_add_edit = QtWidgets.QPushButton(Form)
        self.btn_add_edit.setGeometry(QtCore.QRect(110, 90, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_add_edit.setFont(font)
        self.btn_add_edit.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: #666;\n"
"    color: white;\n"
"    transition: transform 0.2s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  cursor: pointer;\n"
"  background-color: gray;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  transform: scale(0.5);\n"
"  background-color: darkgray;\n"
"}")
        self.btn_add_edit.setObjectName("btn_add_edit")
        self.btn_delete = QtWidgets.QPushButton(Form)
        self.btn_delete.setGeometry(QtCore.QRect(410, 140, 41, 41))
        self.btn_delete.setStyleSheet("background-color: transparent;")
        self.btn_delete.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI/ui\\../icons/addTaskWindow/trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_delete.setIcon(icon)
        self.btn_delete.setIconSize(QtCore.QSize(41, 41))
        self.btn_delete.setObjectName("btn_delete")
        self.btn_delete.setVisible(False)
        self.btn_delete.setEnabled(False)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_add_edit.setText(_translate("Form", "Добавить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_AddCategoryWindow()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
