# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/ui/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("")
        application_icon = QtGui.QIcon()
        application_icon.addPixmap(QtGui.QPixmap(r"UI/icons/toDoList_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(application_icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.list_tasks = QtWidgets.QListWidget(self.centralwidget)
        self.list_tasks.setGeometry(QtCore.QRect(10, 30, 551, 561))
        self.list_tasks.setFocusPolicy(QtCore.Qt.NoFocus)
        self.list_tasks.setStyleSheet("QListWidget {\n"
"  background-color: #212121;\n"
"  border: 1px solid #5a6b91;\n"
"  font-family: \"Arial\", sans-serif;\n"
"  font-size: 16px;\n"
"  color: white;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"  background-color: #303030;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 2px;\n"
"  padding: 10px;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"  background-color: #505050;\n"
"  color: white;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"  background-color: #404040;\n"
"  cursor: pointer;\n"
"}\n"
"\n"
"QListWidget::item:disabled {\n"
"  color: #707070;\n"
"}\n"
"")
        self.list_tasks.setObjectName("list_tasks")
        self.btn_add_task = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_task.setGeometry(QtCore.QRect(574, 40, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_add_task.setFont(font)
        self.btn_add_task.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: #666;\n"
"    color: white;\n"
"    transition: transform 0.2s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  cursor: pointer;\n"
"  background-color: gray;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  transform: scale(0.5);\n"
"  background-color: darkgray;\n"
"}")
        self.btn_add_task.setObjectName("btn_add_task")
        self.btn_add_category = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_category.setGeometry(QtCore.QRect(580, 130, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_add_category.setFont(font)
        self.btn_add_category.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: #666;\n"
"    color: white;\n"
"    transition: transform 0.2s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  cursor: pointer;\n"
"  background-color: gray;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  transform: scale(0.5);\n"
"  background-color: darkgray;\n"
"}")
        self.btn_add_category.setObjectName("btn_add_category")
        self.comboBox_categories = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_categories.setGeometry(QtCore.QRect(10, 0, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_categories.setFont(font)
        self.comboBox_categories.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comboBox_categories.setStyleSheet("background-color: #666;\n"
"color: rgb(255, 255, 255);")
        self.comboBox_categories.setObjectName("comboBox_categories")
        self.comboBox_categories.addItem("")
        self.btn_edit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_edit.setGeometry(QtCore.QRect(329, 1, 30, 28))
        self.btn_edit.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"      background-color: #666;\n"
"   color: white;\n"
"   transition: transform 0.2s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    cursor: pointer;\n"
"    background-color: gray;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    transform: scale(0.5);\n"
"    background-color: darkgray;\n"
"}")
        self.btn_edit.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI/ui\\../icons/mainWindow/pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_edit.setIcon(icon)
        self.btn_edit.setIconSize(QtCore.QSize(25, 25))
        self.btn_edit.setObjectName("btn_edit")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-11, -11, 821, 621))
        self.frame.setStyleSheet("background-color: rgb(33, 33, 33);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(590, 520, 211, 71))
        self.frame_2.setStyleSheet("border-radius: 10px;\n"
"background-color: #333;\n"
"color: white;\n"
"transition: transform 0.2s;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.radBtn_not_finished = QtWidgets.QRadioButton(self.frame_2)
        self.radBtn_not_finished.setGeometry(QtCore.QRect(10, 10, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radBtn_not_finished.setFont(font)
        self.radBtn_not_finished.setChecked(True)
        self.radBtn_not_finished.setObjectName("radBtn_not_finished")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radBtn_not_finished)
        self.radBtn_finished = QtWidgets.QRadioButton(self.frame_2)
        self.radBtn_finished.setGeometry(QtCore.QRect(10, 40, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radBtn_finished.setFont(font)
        self.radBtn_finished.setObjectName("radBtn_finished")
        self.buttonGroup.addButton(self.radBtn_finished)
        self.frame.raise_()
        self.list_tasks.raise_()
        self.btn_add_task.raise_()
        self.btn_add_category.raise_()
        self.comboBox_categories.raise_()
        self.btn_edit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_add_task.setText(_translate("MainWindow", "Добавить задачу"))
        self.btn_add_category.setText(_translate("MainWindow", "Добавить категорию"))
        self.comboBox_categories.setItemText(0, _translate("MainWindow", "Все задачи"))
        self.radBtn_not_finished.setText(_translate("MainWindow", "Не завершённые"))
        self.radBtn_finished.setText(_translate("MainWindow", "Завершённые"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
